---
- name: BIG-IQ and AS3 Lab - Task 8 - Deploy the HTTP Application Service using the Custom Template
  hosts: "{{ env }}"
  vars_files:
    - inventory/group_vars/{{ env }}.yml

  tasks: 
    - name: Get BIG-IQ Token POST /mgmt/shared/authn/login (auth_bigiq_<user>.json)
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/shared/authn/login
        method: POST
        headers:
          Content-Type: application/json
        body: "{{ lookup('file','{{ user }}') }}"
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: auth

    - name: Task 8 - Deploy the HTTP Application Service using the Custom Template - POST /mgmt/shared/appsvcs/declare?async=true
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/shared/appsvcs/declare?async=true
        method: POST
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        body:
          # used https://www.json2yaml.com/ to convert JSON declaration to YAML
          class: AS3
          action: deploy
          declaration:
            class: ADC
            schemaVersion: "{{ as3_schemaVersion }}"
            id: isc-lab
            label: Task8
            target:
              address: "{{ bigip_target_ip }}"
            Task8:
              class: Tenant
              MyWebApp8http:
                class: Application
                schemaOverlay: "{{ task6_bigiq_custom_template }}"
                template: http
                statsProfile:
                  class: Analytics_Profile
                  collectClientSideStatistics: true
                  collectOsAndBrowser: false
                  collectMethod: false
                serviceMain:
                  class: Service_HTTP
                  virtualAddresses:
                  - "{{ task8_vs }}"
                  virtualPort: 8080
                  pool: pool_8
                  profileAnalytics:
                    use: statsProfile
                pool_8:
                  class: Pool
                  monitors:
                  - http
                  members:
                  - servicePort: 80
                    serverAddresses:
                    - "{{ task8_node1 }}"
                    - "{{ task8_node2 }}"
                    shareNodes: true
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: json_response

    - debug:
        var: json_response.json

### LOOP TO CHECK THE TASK - DO NOT MODIFY BELOW

    - name: Check AS3 Deployment Task - GET /mgmt/shared/appsvcs/task/<task_id>
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/shared/appsvcs/task/{{json_response.json.id}}
        method: GET
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: json_response_task

    - debug:
        var: json_response_task.json

    - name: LOOP Check AS3 Deployment Task - GET /mgmt/shared/appsvcs/task/<task_id>
      uri:
        url: https://{{ bigiq_cm_server }}/mgmt/shared/appsvcs/task/{{json_response.json.id}}
        method: GET
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        status_code: 200, 202
        validate_certs: false
      register: json_response_task
      until: "json_response_task.json[0].results != 'pending'"
      retries: 20
      delay: 30

    - debug:
        var: json_response_task.json