---
# BIG-IQ and AS3 Lab - Move App services into Apps
- hosts: f5_bigiq_cm
  connection: local
  serial: 1
  gather_facts: false
  vars:
    provider:
      server: "{{ hostvars[groups['f5_bigiq_cm'][0]]['ansible_host'] }}"
      server_port: 443
      user: admin
      password: "{{ hostvars[groups['f5_bigiq_cm'][0]]['ansible_ssh_pass'] }}"
      loginProviderName: "tmos"
      validate_certs: no

  tasks: 
  - name: Move an AS3 application service in BIG-IQ dashboard.
    include_role:
      name: f5devcentral.bigiq_move_app_dashboard
    vars:
        apps: 
        - name: LAB_task1
            pins:
            - name: Task1_MyWebApp1http
            - name: Task1_MyWebApp6https
    register: status
