---
- name: TOWER-AS3-BIG-IQ - Delete App Service
  hosts: bigiq
  connection: local
  gather_facts: false
  vars:
    provider:
      server: "{{ hostvars[inventory_hostname]['mgmt_ip'] }}"
      server_port: "{{ hostvars[inventory_hostname]['mgmt_port'] }}"
      user: "{{ bigiq_user }}"
      password: "{{ bigiq_pass }}"
      auth_provider: "{{ bigiq_provider }}"
      validate_certs: false

  tasks:
    - debug: var=provider

    - name: Install role from Ansible Galaxy atc_deploy
      command: ansible-galaxy install f5devcentral.atc_deploy --force

    - name: Install role from Ansible Galaxy bigiq_move_app_dashboard
      command: ansible-galaxy install f5devcentral.bigiq_move_app_dashboard --force

    - name: AS3 deploy
      include_role:
        name: f5devcentral.atc_deploy
      vars:
        atc_service: AS3
        atc_method: POST
        atc_declaration: "{{ lookup('template','j2/delete_app.j2') }}"
        atc_delay: 15
        atc_retries: 30
      register: atc_AS3_status

    - debug: var=atc_AS3_status
